#!/usr/bin/env bash
# Write homepage-webserver-ansible inventory from terraform output.
# Regenerates every mapped environment file; hosts not in state are removed.
#
# Usage (from azure-tf-architecture root):
#   ./scripts/sync-ansible-inventory.sh
#   ANSIBLE_REPO=../homepage-webserver-ansible ./scripts/sync-ansible-inventory.sh
#
# Requires: terraform, jq

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ANSIBLE_REPO="${ANSIBLE_REPO:-$ROOT_DIR/../homepage-webserver-ansible}"

declare -A ENV_MAP=(
  [dev]=development
  [tst]=test
  [prd]=production
)

if ! command -v terraform >/dev/null 2>&1; then
  echo "terraform is required." >&2
  exit 1
fi

if ! command -v jq >/dev/null 2>&1; then
  echo "jq is required." >&2
  exit 1
fi

if [[ ! -d "$ANSIBLE_REPO" ]]; then
  echo "Ansible repo not found at: $ANSIBLE_REPO" >&2
  echo "Set ANSIBLE_REPO to the homepage-webserver-ansible path." >&2
  exit 1
fi

cd "$ROOT_DIR"

hosts_json="$(terraform output -json ansible_hosts_out 2>/dev/null || echo '[]')"

write_inventory() {
  local env_key="$1"
  local inventory_name="${ENV_MAP[$env_key]:-$env_key}"
  local inventory_file="$ANSIBLE_REPO/inventory/$inventory_name"
  local tmp
  tmp="$(mktemp)"

  mkdir -p "$(dirname "$inventory_file")"

  {
    echo "# Generated by azure-tf-architecture/scripts/sync-ansible-inventory.sh"
    echo "# Do not edit by hand — re-run the script after terraform apply."
    echo
    echo "[servers]"
  } >"$tmp"

  mapfile -t server_lines < <(echo "$hosts_json" | jq -r --arg env "$env_key" '
    .[] | select(.environment == $env and .public_ip != null and .public_ip != "")
    | "\(.public_ip) ansible_user=\(.admin_user)"
  ')

  if ((${#server_lines[@]})); then
    printf '%s\n' "${server_lines[@]}" >>"$tmp"
  else
    echo "# (no hosts in terraform state for environment: ${env_key})" >>"$tmp"
  fi

  {
    echo
    echo "[nginx]"
  } >>"$tmp"

  mapfile -t nginx_lines < <(echo "$hosts_json" | jq -r --arg env "$env_key" '
    .[] | select(.environment == $env and .service == "nginx" and .public_ip != null and .public_ip != "")
    | "\(.public_ip) ansible_user=\(.admin_user)"
  ')

  if ((${#nginx_lines[@]})); then
    printf '%s\n' "${nginx_lines[@]}" >>"$tmp"
  else
    echo "# (no nginx hosts in terraform state for environment: ${env_key})" >>"$tmp"
  fi

  mv "$tmp" "$inventory_file"
  echo "Wrote $inventory_file (${#server_lines[@]} server, ${#nginx_lines[@]} nginx)"
}

for env_key in "${!ENV_MAP[@]}"; do
  write_inventory "$env_key"
done
