#!/usr/bin/env bash
# Write homepage-webserver-ansible firewall_allowed_ips from terraform output.
# admin_allowed_ips in terraform is the single source of truth for the SSH/ICMP
# allowlist (NSG rules flagged admin_restricted). This mirrors it into Ansible so
# the host firewall (UFW) matches the cloud firewall (NSG).
#
# Usage (from azure-tf-architecture root):
#   ./scripts/sync-firewall-allowlist.sh
#   ANSIBLE_REPO=../homepage-webserver-ansible ./scripts/sync-firewall-allowlist.sh
#
# Requires: terraform, jq

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ANSIBLE_REPO="${ANSIBLE_REPO:-$ROOT_DIR/../homepage-webserver-ansible}"
OUT_FILE="$ANSIBLE_REPO/group_vars/servers/firewall_allowed_ips.yml"

for cmd in terraform jq; do
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "$cmd is required." >&2
    exit 1
  fi
done

if [[ ! -d "$ANSIBLE_REPO" ]]; then
  echo "Ansible repo not found at: $ANSIBLE_REPO" >&2
  echo "Set ANSIBLE_REPO to the homepage-webserver-ansible path." >&2
  exit 1
fi

cd "$ROOT_DIR"

ips_json="$(terraform output -json admin_allowed_ips_out 2>/dev/null || echo '[]')"

mkdir -p "$(dirname "$OUT_FILE")"
tmp="$(mktemp)"

{
  echo "# Generated by azure-tf-architecture/scripts/sync-firewall-allowlist.sh"
  echo "# Do not edit by hand — re-run the script after terraform apply."
  echo "firewall_allowed_ips:"
} >"$tmp"

count="$(echo "$ips_json" | jq 'length')"
if [[ "$count" -gt 0 ]]; then
  echo "$ips_json" | jq -r '.[] | "  - \(.)"' >>"$tmp"
else
  echo "  [] # no admin_allowed_ips in terraform output" >>"$tmp"
fi

mv "$tmp" "$OUT_FILE"
echo "Wrote $OUT_FILE (${count} ip(s))"
